package com.example;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.http.MediaType;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class StatusController {

    @GetMapping(value = "/", produces = MediaType.TEXT_HTML_VALUE)
    public String home() {
        return "<!doctype html>"
            + "<html lang=\"en\">"
            + "<head>"
            + "  <meta charset=\"utf-8\" />"
            + "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />"
            + "  <title>Profilio Vishal Kolan</title>"
            + "  <meta name=\"description\" content=\"My first portfolio page.\" />"
            + "  <style>"
            + "    :root {"
            + "      --ink: #111317;"
            + "      --paper: #f7f2e9;"
            + "      --sun: #f8c85e;"
            + "      --clay: #d9815d;"
            + "      --slate: #5a6b7a;"
            + "      --shadow: rgba(17, 19, 23, 0.18);"
            + "      --radius-lg: 24px;"
            + "      --radius-md: 16px;"
            + "    }"
            + "    * { box-sizing: border-box; }"
            + "    body {"
            + "      margin: 0;"
            + "      font-family: \"Space Grotesk\", system-ui, -apple-system, sans-serif;"
            + "      color: var(--ink);"
            + "      background:"
            + "        radial-gradient(800px 400px at 10% -10%, #fdebd0 0%, transparent 70%),"
            + "        radial-gradient(700px 500px at 110% 10%, #f7d8c6 0%, transparent 65%),"
            + "        linear-gradient(180deg, #faf6f0 0%, #f0e9df 100%);"
            + "      min-height: 100vh;"
            + "    }"
            + "    header { padding: 32px 24px 12px; }"
            + "    .nav {"
            + "      max-width: 1120px;"
            + "      margin: 0 auto;"
            + "      display: flex;"
            + "      align-items: center;"
            + "      justify-content: space-between;"
            + "      gap: 16px;"
            + "    }"
            + "    .brand {"
            + "      display: flex;"
            + "      align-items: center;"
            + "      gap: 12px;"
            + "      font-weight: 700;"
            + "      letter-spacing: 0.5px;"
            + "    }"
            + "    .brand-badge {"
            + "      width: 40px;"
            + "      height: 40px;"
            + "      border-radius: 12px;"
            + "      background: linear-gradient(135deg, var(--sun), var(--clay));"
            + "      box-shadow: 0 12px 22px var(--shadow);"
            + "      display: grid;"
            + "      place-items: center;"
            + "      font-weight: 700;"
            + "    }"
            + "    .hero {"
            + "      max-width: 1120px;"
            + "      margin: 0 auto;"
            + "      padding: 48px 24px 64px;"
            + "      display: grid;"
            + "      grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));"
            + "      gap: 32px;"
            + "      align-items: center;"
            + "    }"
            + "    .hero h1 {"
            + "      font-family: \"Playfair Display\", serif;"
            + "      font-size: clamp(2.6rem, 4vw, 4.1rem);"
            + "      line-height: 1.05;"
            + "      margin: 0 0 18px;"
            + "    }"
            + "    .hero p { color: var(--slate); font-size: 1.05rem; margin: 0 0 24px; }"
            + "    .cta { display: flex; flex-wrap: wrap; gap: 14px; }"
            + "    .btn {"
            + "      border: none;"
            + "      border-radius: 999px;"
            + "      padding: 12px 22px;"
            + "      font-weight: 600;"
            + "      text-decoration: none;"
            + "      display: inline-flex;"
            + "      align-items: center;"
            + "      gap: 8px;"
            + "    }"
            + "    .btn.primary { background: var(--ink); color: var(--paper); }"
            + "    .btn.ghost { background: transparent; color: var(--ink); border: 1px solid rgba(17, 19, 23, 0.2); }"
            + "    .panel {"
            + "      background: rgba(255, 255, 255, 0.8);"
            + "      border-radius: var(--radius-lg);"
            + "      padding: 28px;"
            + "      box-shadow: 0 20px 50px var(--shadow);"
            + "    }"
            + "    .grid {"
            + "      display: grid;"
            + "      grid-template-columns: repeat(auto-fit, minmax(240px, 1fr));"
            + "      gap: 18px;"
            + "    }"
            + "    .card {"
            + "      background: #fff;"
            + "      border-radius: var(--radius-md);"
            + "      padding: 20px;"
            + "      border: 1px solid rgba(17, 19, 23, 0.08);"
            + "      box-shadow: 0 10px 20px rgba(17, 19, 23, 0.08);"
            + "    }"
            + "    footer { padding: 24px; color: var(--slate); text-align: center; font-size: 0.9rem; }"
            + "    @media (max-width: 860px) { .nav { flex-wrap: wrap; } }"
            + "  </style>"
            + "</head>"
            + "<body>"
            + "  <header>"
            + "    <nav class=\"nav\">"
            + "      <div class=\"brand\">"
            + "        <div class=\"brand-badge\">VK</div>"
            + "        <span>Profilio Vishal Kolan</span>"
            + "      </div>"
            + "    </nav>"
            + "  </header>"
            + "  <main>"
            + "    <section class=\"hero\">"
            + "      <div>"
            + "        <p style=\"font-weight:600; color:#2c5d63;\">My first portfolio page</p>"
            + "        <h1>Hello, I am Vishal Kolan.</h1>"
            + "        <p>I build clean, reliable software and love learning new technologies.</p>"
            + "        <div class=\"cta\">"
            + "          <a class=\"btn primary\" href=\"#projects\">View projects</a>"
            + "          <a class=\"btn ghost\" href=\"#contact\">Contact me</a>"
            + "        </div>"
            + "      </div>"
            + "      <div class=\"panel\">"
            + "        <h2>Quick intro</h2>"
            + "        <p>Student / Developer | Java, Spring Boot, GitHub Actions</p>"
            + "        <div class=\"grid\" style=\"margin-top:16px;\">"
            + "          <div class=\"card\"><strong>Skills</strong><p>Java, Spring Boot, Git, Docker</p></div>"
            + "          <div class=\"card\"><strong>Focus</strong><p>CI/CD, clean APIs, reliability</p></div>"
            + "        </div>"
            + "      </div>"
            + "    </section>"
            + "    <section id=\"projects\" style=\"max-width:1120px;margin:0 auto;padding:0 24px 48px;\">"
            + "      <h2>Projects</h2>"
            + "      <div class=\"grid\">"
            + "        <div class=\"card\"><h3>CI/CD Demo App</h3><p>Automated builds and Docker packaging.</p></div>"
            + "        <div class=\"card\"><h3>Portfolio Page</h3><p>A simple and modern personal landing page.</p></div>"
            + "        <div class=\"card\"><h3>Next Project</h3><p>Coming soon.</p></div>"
            + "      </div>"
            + "    </section>"
            + "    <section id=\"contact\" style=\"max-width:1120px;margin:0 auto;padding:0 24px 64px;\">"
            + "      <div class=\"panel\">"
            + "        <h2>Contact</h2>"
            + "        <p>Email: vkreddy7416@gamil.com</p>"
            + "      </div>"
            + "    </section>"
            + "  </main>"
            + "  <footer>Profilio Vishal Kolan</footer>"
            + "</body>"
            + "</html>";
    }

    @GetMapping("/status")
    public String status() {
        return "OK";
    }
}
