# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-java:

    runs-on: ubuntu-latest
    environment: Docker 

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run tests
      run: ./gradlew clean test

    - name: Build boot jar
      run: ./gradlew bootJar

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          kolan7416/java-gradle:latest
          kolan7416/java-gradle:v1

    - uses: actions/checkout@v4
      with:
        repository: medyagh/local-dev-example-with-minikube
    - name: Start minikube
      uses: medyagh/setup-minikube@latest
    - name: Try the cluster!
      run: kubectl get pods -A

    - uses: actions/checkout@v4

    - name: Deploy to minikube
      run: |
        kubectl apply -f minikube/deploymentyaml
        kubectl wait --for=condition=ready pod -l app=my-portfolio
    - name: Test service URLs
      run: |
        minikube service list
        minikube service my-portfolio-service --url
        echo "------------------opening the service------------------"
        curl $(minikube service my-portfolio-service --url)